### PR TITLE
Add linking feature

### PR DESCRIPTION
**Pull request by scinscinscin**

### CODE REVIEW

**Comment by WarenGonzaga** [comment]
@scinscinscin what is this?

**Comment by WarenGonzaga** [comment]
Is this unstable feature? @scinscinscin

**Comment by scinscinscin** [comment]
this adds the feature to npm link the CLI to the ``covid`` command that is not currently present in v4. It is a stable feature.

**Comment by WarenGonzaga** [comment]
alright will merge this one @scinscinscin

**Pull request merged**
